version: '2'
services:
  mocks:
    build: ./mocks
    command: npm run start
    environment:
      DPI_HOST: ${DPI_HOST}
    ports:
      - ${MOCK_PORT}:${MOCK_PORT}

  sa-mock:
    build: ./move-sakarkiv-mock
    command: npm run start
    ports:
      - ${SA_MOCK_PORT}:${SA_MOCK_PORT}

  wiremock:
    build: ./Wiremock
    ports:
      - ${WIREMOCK_PORT}:${WIREMOCK_PORT}

  dpimock:
    build: ./dpimock
    command:  cd ./dpimock && ./mvnw install dockerfile:build
    ports:
      - ${DPI_PORT}:${DPI_PORT}
